version: "3"
services:
  betcr-scheduled-server:
    restart: always
    
    build:
      context: .
      target: scheduled
    ports:
      - 127.0.0.1:5002:5002
    environment:
      - BETCR_ENVIRONMENT=Production
    volumes:
      - ~/source/repos/BetCR/DB:/DB

  betcr-app-server:
    restart: always
    build: 
      context: .
      target: final
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5000;http://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=p123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/source/repos/BetCR/DB:/DB


    
